<template>
  <div class="min-h-screen flex items-center justify-center bg-gradient-to-b from-indigo-500 via-sky-400 to-teal-300">
    <div class="container mx-auto px-4 py-16">
      <div class="text-center text-black">
        <h1 class="text-6xl font-bold mb-6">AvenTra</h1>
        <h2 class="text-5xl font-bold mb-6">Plan Your Perfect Trip</h2>
        <p class="text-xl mb-8">AI-powered travel planning made simple</p>
        <div class="space-x-4">
          <router-link to="/register" class="bg-white text-blue-600 px-8 py-3 rounded-lg font-semibold hover:bg-gray-100">
            Get Started
          </router-link>
          <router-link to="/login" class="border-2 border-white text-white px-8 py-3 rounded-lg font-semibold hover:bg-white hover:text-blue-600">
            Login
          </router-link>
        </div>
      </div>
      
      <div class="mt-16 grid md:grid-cols-3 gap-8">
        <div class="bg-white p-6 rounded-lg shadow-lg">
          <div class="text-blue-600 text-3xl mb-4">🤖</div>
          <h3 class="text-xl font-semibold mb-2">AI-Powered Planning</h3>
          <p class="text-gray-600">Get personalized itineraries generated by AI based on your preferences</p>
        </div>
        <div class="bg-white p-6 rounded-lg shadow-lg">
          <div class="text-blue-600 text-3xl mb-4">📍</div>
          <h3 class="text-xl font-semibold mb-2">Real-time Updates</h3>
          <p class="text-gray-600">Stay informed with live location data and dynamic recommendations</p>
        </div>
        <div class="bg-white p-6 rounded-lg shadow-lg">
          <div class="text-blue-600 text-3xl mb-4">🛡️</div>
          <h3 class="text-xl font-semibold mb-2">Safety First</h3>
          <p class="text-gray-600">Emergency contacts and location sharing for peace of mind</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Home'
}
</script>